blank_issues_enabled: false
contact_links:
  - name: 💬 Contact the author
    url: mailto:johnjacobgonzales12678@gmail.com
    about: For general questions, opportunities, or private/security matters.
  - name: 🔗 LinkedIn
    url: https://linkedin.com/in/johnjacobgonzales
    about: Connect or message directly.
